name: ai_chat_bot
description: A Flutter AI chat bot application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  logger: ^2.0.2
  http: ^1.1.0
  uuid: ^3.0.7
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.0
  # Firebase dependencies have been removed
  url_launcher: ^6.1.12
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Add dependency overrides to address discontinued and outdated packages
dependency_overrides:
  # Override for discontinued js package
  js: ^0.7.2
  # Overrides for other key outdated transitive dependencies
  archive: ^4.0.5
  intl: ^0.20.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - .env
