name: chatbot_app
description: A simple chatbot app using DeepSeek API
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0" # Updated Dart SDK constraint

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  logger: ^2.5.0
  shared_preferences: ^2.5.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  uuid: ^4.3.2 # Added for generating unique IDs for chat sessions

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/